In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import numpy as np

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [3]:
model_logi = LogisticRegression(max_iter = 1000, verbose = 1)

In [4]:
model_logi.fit(x_data, y_data)

C:\Users\13a71\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [5]:
model_logi.coef_

array([[0., 0.]])

In [6]:
model_logi.intercept_

array([0.])

In [7]:
model_logi.predict(x_data)

array([0, 0, 0, 0])

In [8]:
from sklearn.metrics import accuracy_score
accuracy_score(y_data,  model_logi.predict(x_data))

0.5

In [9]:
model_mlp = MLPClassifier(verbose = True, hidden_layer_sizes= (100,), max_iter= 1000)

In [10]:
model_mlp.fit(x_data, y_data)

C:\Users\13a71\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Iteration 1, loss = 0.68746950
Iteration 2, loss = 0.68598888
Iteration 3, loss = 0.68455925
Iteration 4, loss = 0.68316283
Iteration 5, loss = 0.68181282
Iteration 6, loss = 0.68045657
Iteration 7, loss = 0.67911315
Iteration 8, loss = 0.67788304
Iteration 9, loss = 0.67660360
Iteration 10, loss = 0.67537142
Iteration 11, loss = 0.67417701
Iteration 12, loss = 0.67298604
Iteration 13, loss = 0.67187290
Iteration 14, loss = 0.67075937
Iteration 15, loss = 0.66967082
Iteration 16, loss = 0.66860628
Iteration 17, loss = 0.66753631
Iteration 18, loss = 0.66645884
Iteration 19, loss = 0.66538722
Iteration 20, loss = 0.66436662
Iteration 21, loss = 0.66337637
Iteration 22, loss = 0.66239126
Iteration 23, loss = 0.66138250
Iteration 24, loss = 0.66036151
Iteration 25, loss = 0.65933905
Iteration 26, loss = 0.65830272
Iteration 27, loss = 0.65727767
Iteration 28, loss = 0.65624483
Iteration 29, loss = 0.65522089
Iteration 30, loss = 0.65420034
Iteration 31, loss = 0.65315860
Iteration 32, los

Iteration 454, loss = 0.10060345
Iteration 455, loss = 0.10008061
Iteration 456, loss = 0.09957063
Iteration 457, loss = 0.09906968
Iteration 458, loss = 0.09855157
Iteration 459, loss = 0.09805360
Iteration 460, loss = 0.09754054
Iteration 461, loss = 0.09703867
Iteration 462, loss = 0.09654336
Iteration 463, loss = 0.09607220
Iteration 464, loss = 0.09557229
Iteration 465, loss = 0.09508641
Iteration 466, loss = 0.09461132
Iteration 467, loss = 0.09412679
Iteration 468, loss = 0.09365142
Iteration 469, loss = 0.09317903
Iteration 470, loss = 0.09270115
Iteration 471, loss = 0.09225009
Iteration 472, loss = 0.09179357
Iteration 473, loss = 0.09132683
Iteration 474, loss = 0.09086089
Iteration 475, loss = 0.09038828
Iteration 476, loss = 0.08991518
Iteration 477, loss = 0.08944874
Iteration 478, loss = 0.08898533
Iteration 479, loss = 0.08851353
Iteration 480, loss = 0.08805248
Iteration 481, loss = 0.08759368
Iteration 482, loss = 0.08713756
Iteration 483, loss = 0.08668080
Iteration 

MLPClassifier(max_iter=1000, verbose=True)

In [11]:
model_mlp.predict(x_data) # x_data = (4,2) w = (2, 100)  x_data @ w = (4,100) x_DATA @ 100 * 1 = (4*1)

array([0, 1, 1, 0])

In [12]:
len(model_mlp.coefs_)

2

In [13]:
model_mlp.coefs_[0].shape

(2, 100)

In [14]:
model_mlp.score(x_data, y_data)

1.0

In [15]:
model_mlp1 = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, verbose = True) # 4 *2 2*100
model_mlp1.fit(x_data, y_data)

Iteration 1, loss = 0.70272275
Iteration 2, loss = 0.69576948
Iteration 3, loss = 0.68941623
Iteration 4, loss = 0.68347509
Iteration 5, loss = 0.67795941
Iteration 6, loss = 0.67310916
Iteration 7, loss = 0.66851991
Iteration 8, loss = 0.66415672
Iteration 9, loss = 0.66035275
Iteration 10, loss = 0.65692036
Iteration 11, loss = 0.65353779
Iteration 12, loss = 0.65017825
Iteration 13, loss = 0.64670388
Iteration 14, loss = 0.64327055
Iteration 15, loss = 0.64010072
Iteration 16, loss = 0.63683215
Iteration 17, loss = 0.63331672
Iteration 18, loss = 0.62967376
Iteration 19, loss = 0.62591468
Iteration 20, loss = 0.62206154
Iteration 21, loss = 0.61830692
Iteration 22, loss = 0.61464020
Iteration 23, loss = 0.61076468
Iteration 24, loss = 0.60682700
Iteration 25, loss = 0.60282444
Iteration 26, loss = 0.59875892
Iteration 27, loss = 0.59470608
Iteration 28, loss = 0.59061033
Iteration 29, loss = 0.58646705
Iteration 30, loss = 0.58242342
Iteration 31, loss = 0.57828797
Iteration 32, los

C:\Users\13a71\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, verbose=True)

In [16]:
##feature data의 수, weight의 수
model_mlp1.coefs_[0].shape

(2, 100)

In [17]:
## weight의 수 * wight2의 수
model_mlp1.coefs_[1].shape

(100, 50)

In [18]:
# wight2의 수 * label
model_mlp1.coefs_[2].shape

(50, 1)

In [19]:
model_mlp1.predict(x_data) # 4*2 @  2* 100 = 4* 100 / 100 * 50 

array([0, 1, 1, 0])

In [20]:
model_mlp2 = MLPClassifier(hidden_layer_sizes= (64, 32, 16),
                          max_iter= 1000, verbose=True)

In [21]:
model_mlp2.fit(x_data, y_data)

C:\Users\13a71\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Iteration 1, loss = 0.70057649
Iteration 2, loss = 0.69699104
Iteration 3, loss = 0.69358636
Iteration 4, loss = 0.69043317
Iteration 5, loss = 0.68747478
Iteration 6, loss = 0.68461984
Iteration 7, loss = 0.68202561
Iteration 8, loss = 0.67967773
Iteration 9, loss = 0.67725884
Iteration 10, loss = 0.67448531
Iteration 11, loss = 0.67160152
Iteration 12, loss = 0.66910226
Iteration 13, loss = 0.66681960
Iteration 14, loss = 0.66451196
Iteration 15, loss = 0.66235519
Iteration 16, loss = 0.66019914
Iteration 17, loss = 0.65794235
Iteration 18, loss = 0.65571934
Iteration 19, loss = 0.65356089
Iteration 20, loss = 0.65161808
Iteration 21, loss = 0.64928424
Iteration 22, loss = 0.64668587
Iteration 23, loss = 0.64418337
Iteration 24, loss = 0.64195884
Iteration 25, loss = 0.64015280
Iteration 26, loss = 0.63799691
Iteration 27, loss = 0.63581171
Iteration 28, loss = 0.63355067
Iteration 29, loss = 0.63099540
Iteration 30, loss = 0.62852114
Iteration 31, loss = 0.62648326
Iteration 32, los

Iteration 253, loss = 0.01207217
Iteration 254, loss = 0.01191296
Iteration 255, loss = 0.01176126
Iteration 256, loss = 0.01161080
Iteration 257, loss = 0.01146126
Iteration 258, loss = 0.01131965
Iteration 259, loss = 0.01117783
Iteration 260, loss = 0.01104010
Iteration 261, loss = 0.01090118
Iteration 262, loss = 0.01076367
Iteration 263, loss = 0.01062852
Iteration 264, loss = 0.01049819
Iteration 265, loss = 0.01036909
Iteration 266, loss = 0.01024137
Iteration 267, loss = 0.01011591
Iteration 268, loss = 0.00999348
Iteration 269, loss = 0.00987172
Iteration 270, loss = 0.00975391
Iteration 271, loss = 0.00963773
Iteration 272, loss = 0.00952264
Iteration 273, loss = 0.00940965
Iteration 274, loss = 0.00929853
Iteration 275, loss = 0.00919026
Iteration 276, loss = 0.00908314
Iteration 277, loss = 0.00897754
Iteration 278, loss = 0.00887408
Iteration 279, loss = 0.00877361
Iteration 280, loss = 0.00867407
Iteration 281, loss = 0.00857568
Iteration 282, loss = 0.00847858
Iteration 

MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000, verbose=True)