# Cost function using TF

In [44]:
import tensorflow as tf
from tensorflow.keras.optimizers import SGD

In [20]:
x_data = [1,2,3]
y_data = [1,2,3]

In [37]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)
w = 3

In [39]:
hx = w * x # tf.multiply( w, x)
sq = tf.square(hx - y) #( hx-y) ** 2
cost = tf.reduce_mean( sq)

In [32]:
hx.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 6., 9.], dtype=float32)>>

In [33]:
sq.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 6.], dtype=float32)>>

In [34]:
cost.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=float32, numpy=4.0>>

In [35]:
def cost(x, y, w):
    hx = w * x
    cost = tf.reduce_mean(tf.square(hx - y))
    return cost

In [29]:
cost(x, y, 3)

<tf.Tensor: shape=(), dtype=float32, numpy=18.666666>

In [30]:
cost(x, y, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

# gradient using TF

## history of optimizer

- GD: 모든 자료를 검토하여 내 위치의 산 기울기를 계산하여 방향을 찾는다.
- SGD: 확률을 이용해서 모든 step을 다 보지 않고, 수렴시킴.
- momentum: 관성의 법직을 이용. 기존 가는 방향에 가중치를 부여.
- 

일반적으로는 optimizer를 ADAM이 goodness

In [54]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [55]:
## 값이 계속 바뀌는 부분은 항상 constant가 아니라 variable을 찾는다

w = tf.Variable(10.0)
b = tf.Variable(10.0)

In [63]:
def compute_cost():
    hx = w * x + b
    cost = tf.reduce_mean(( hx - y) ** 2)
    return cost

In [60]:
optimizer = SGD(learning_rate = 0.01) # 미분 + a


In [65]:
for i in range(2000):
    optimizer.minimize(compute_cost, var_list = [w, b])
    # w = w- 0.01 * w에 대한 미분값.w.assign_sub(0.01 * 미분값) 미분한 값으로 계속 주기적으로 바꿔주는 것.
    # b = b -0*x에 대한 미분값. b.assign_sub(0.01 * 미분값) 미분한 값으로 계속 주기적으로 바꿔주는 것.
    print(i, "cost", compute_cost().numpy())

0 cost 524.93085
1 cost 415.67505
2 cost 329.31052
3 cost 261.0405
4 cost 207.07307
5 cost 164.4113
6 cost 130.68587
7 cost 104.02423
8 cost 82.94617
9 cost 66.281624
10 cost 53.105747
11 cost 42.68749
12 cost 34.44901
13 cost 27.933538
14 cost 22.78003
15 cost 18.703093
16 cost 15.477145
17 cost 12.923878
18 cost 10.902341
19 cost 9.301129
20 cost 8.032173
21 cost 7.025865
22 cost 6.2271843
23 cost 5.592633
24 cost 5.087836
25 cost 4.685616
26 cost 4.3644958
27 cost 4.107494
28 cost 3.9011905
29 cost 3.7349758
30 cost 3.600463
31 cost 3.491027
32 cost 3.4014246
33 cost 3.3275175
34 cost 3.2660286
35 cost 3.2143726
36 cost 3.1705027
37 cost 3.132801
38 cost 3.0999916
39 cost 3.071062
40 cost 3.045214
41 cost 3.021817
42 cost 3.0003703
43 cost 2.9804804
44 cost 2.9618342
45 cost 2.9441864
46 cost 2.9273407
47 cost 2.9111433
48 cost 2.8954718
49 cost 2.88023
50 cost 2.8653421
51 cost 2.8507464
52 cost 2.8363965
53 cost 2.8222544
54 cost 2.8082886
55 cost 2.7944767
56 cost 2.7807999
57 co

495 cost 0.33594355
496 cost 0.3343303
497 cost 0.3327249
498 cost 0.33112702
499 cost 0.329537
500 cost 0.3279545
501 cost 0.32637957
502 cost 0.3248123
503 cost 0.32325256
504 cost 0.3217003
505 cost 0.32015547
506 cost 0.31861803
507 cost 0.31708798
508 cost 0.31556532
509 cost 0.3140499
510 cost 0.3125418
511 cost 0.31104097
512 cost 0.30954728
513 cost 0.30806085
514 cost 0.3065815
515 cost 0.30510932
516 cost 0.30364415
517 cost 0.30218604
518 cost 0.3007349
519 cost 0.29929075
520 cost 0.29785356
521 cost 0.29642323
522 cost 0.29499975
523 cost 0.2935831
524 cost 0.29217336
525 cost 0.29077026
526 cost 0.28937402
527 cost 0.28798437
528 cost 0.2866014
529 cost 0.28522512
530 cost 0.28385547
531 cost 0.2824923
532 cost 0.28113577
533 cost 0.27978572
534 cost 0.27844217
535 cost 0.27710518
536 cost 0.27577448
537 cost 0.2744502
538 cost 0.27313223
539 cost 0.27182057
540 cost 0.2705154
541 cost 0.26921636
542 cost 0.26792353
543 cost 0.26663685
544 cost 0.2653565
545 cost 0.264082

964 cost 0.03514002
965 cost 0.034971263
966 cost 0.03480333
967 cost 0.034636226
968 cost 0.034469873
969 cost 0.03430434
970 cost 0.034139615
971 cost 0.03397569
972 cost 0.03381252
973 cost 0.033650164
974 cost 0.03348856
975 cost 0.033327732
976 cost 0.03316771
977 cost 0.03300843
978 cost 0.03284993
979 cost 0.032692164
980 cost 0.032535188
981 cost 0.032378957
982 cost 0.032223452
983 cost 0.03206871
984 cost 0.031914722
985 cost 0.031761456
986 cost 0.03160895
987 cost 0.031457175
988 cost 0.03130608
989 cost 0.031155748
990 cost 0.031006142
991 cost 0.03085728
992 cost 0.030709088
993 cost 0.03056164
994 cost 0.030414866
995 cost 0.03026881
996 cost 0.03012345
997 cost 0.029978795
998 cost 0.029834813
999 cost 0.029691583
1000 cost 0.029548978
1001 cost 0.029407086
1002 cost 0.02926585
1003 cost 0.02912535
1004 cost 0.02898545
1005 cost 0.028846266
1006 cost 0.028707748
1007 cost 0.028569879
1008 cost 0.028432718
1009 cost 0.028296182
1010 cost 0.028160302
1011 cost 0.028025059

1392 cost 0.0044776467
1393 cost 0.004456144
1394 cost 0.0044347444
1395 cost 0.004413443
1396 cost 0.0043922546
1397 cost 0.004371167
1398 cost 0.0043501677
1399 cost 0.004329281
1400 cost 0.0043084905
1401 cost 0.0042878008
1402 cost 0.0042672125
1403 cost 0.0042467117
1404 cost 0.004226325
1405 cost 0.0042060297
1406 cost 0.0041858247
1407 cost 0.004165732
1408 cost 0.0041457266
1409 cost 0.0041258186
1410 cost 0.004106009
1411 cost 0.0040862933
1412 cost 0.004066663
1413 cost 0.0040471386
1414 cost 0.00402771
1415 cost 0.004008355
1416 cost 0.0039891144
1417 cost 0.003969959
1418 cost 0.0039508953
1419 cost 0.0039319186
1420 cost 0.0039130407
1421 cost 0.0038942571
1422 cost 0.003875547
1423 cost 0.0038569402
1424 cost 0.003838422
1425 cost 0.0038199888
1426 cost 0.0038016445
1427 cost 0.0037833906
1428 cost 0.0037652228
1429 cost 0.0037471403
1430 cost 0.0037291523
1431 cost 0.0037112404
1432 cost 0.0036934072
1433 cost 0.0036756732
1434 cost 0.003658022
1435 cost 0.0036404592
143

1802 cost 0.000622201
1803 cost 0.0006192092
1804 cost 0.0006162356
1805 cost 0.0006132757
1806 cost 0.00061033363
1807 cost 0.00060739956
1808 cost 0.000604485
1809 cost 0.0006015843
1810 cost 0.00059869234
1811 cost 0.0005958204
1812 cost 0.00059295824
1813 cost 0.0005901087
1814 cost 0.0005872753
1815 cost 0.0005844585
1816 cost 0.0005816505
1817 cost 0.00057885575
1818 cost 0.0005760766
1819 cost 0.0005733101
1820 cost 0.00057055714
1821 cost 0.0005678152
1822 cost 0.0005650902
1823 cost 0.000562377
1824 cost 0.00055967626
1825 cost 0.00055698905
1826 cost 0.000554316
1827 cost 0.0005516528
1828 cost 0.0005490035
1829 cost 0.0005463657
1830 cost 0.00054374477
1831 cost 0.00054113247
1832 cost 0.00053853355
1833 cost 0.00053594826
1834 cost 0.00053337304
1835 cost 0.0005308152
1836 cost 0.0005282644
1837 cost 0.00052572426
1838 cost 0.0005232026
1839 cost 0.00052068883
1840 cost 0.0005181903
1841 cost 0.0005156974
1842 cost 0.00051322306
1843 cost 0.0005107593
1844 cost 0.0005083074