In [1]:
import numpy as np
import math

# softmax function

In [2]:
def fn(x):
    print(x/x.sum())

In [3]:
def softmax( x ):
    e = np.exp( x )
    print(e)
    print('=====================')
    print(e/e.sum())

In [4]:
arr = np.array([2.0, 1.0, 0.1])
#fn(arr)
softmax(arr)

[7.3890561  2.71828183 1.10517092]
[0.65900114 0.24243297 0.09856589]


In [5]:
import tensorflow as tf
import pandas as pd

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from sklearn.preprocessing import MinMaxScaler, StandardScaler

from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.pipeline import make_pipeline

from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('~/dropbox/python숙달/data/depp/softmax.txt', header = None, sep = ' ')
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [7]:
X_data = df.iloc[:, 0:2]
y_data = df.iloc[:, 2:]

In [8]:
y_data

2  3  4
0  0  0  1
1  0  0  1
2  0  0  1
3  0  1  0
4  0  1  0
5  0  1  0
6  1  0  0
7  1  0  0

In [24]:
X_data

0  1
0  2  1
1  3  2
2  3  4
3  5  5
4  7  5
5  2  5
6  6  6
7  7  7

# Tensorflow version

In [10]:
X = tf.constant(X_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [11]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape=[2,3]))
b = tf.Variable(initX(shape = [3]))

In [12]:
def compute_loss():
    z = tf.matmul( X, w) + b
    cost_i = tf.nn.softmax_cross_entropy_with_logits(labels = y, logits = z)
    cost = tf.reduce_mean( cost_i)
    return cost

In [14]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss, var_list= [w, b])
    print(i, "cost :", compute_loss().numpy())


0 cost : 2.7959342
1 cost : 2.4017444
2 cost : 2.0032115
3 cost : 1.6255016
4 cost : 1.2933129
5 cost : 1.183087
6 cost : 1.50722
7 cost : 1.6452472
8 cost : 1.4931793
9 cost : 1.2454607
10 cost : 1.0953848
11 cost : 1.0819511
12 cost : 1.1231095
13 cost : 1.1668687
14 cost : 1.1941212
15 cost : 1.1933727
16 cost : 1.1619577
17 cost : 1.1081363
18 cost : 1.0440748
19 cost : 0.9804807
20 cost : 0.9293057
21 cost : 0.9057207
22 cost : 0.9163526
23 cost : 0.9416124
24 cost : 0.9467721
25 cost : 0.9180035
26 cost : 0.8726291
27 cost : 0.836246
28 cost : 0.8197123
29 cost : 0.8177012
30 cost : 0.8200689
31 cost : 0.81974673
32 cost : 0.81357384
33 cost : 0.800837
34 cost : 0.78302515
35 cost : 0.7638846
36 cost : 0.7479876
37 cost : 0.7383477
38 cost : 0.7347753
39 cost : 0.7339113
40 cost : 0.73117924
41 cost : 0.723879
42 cost : 0.7129327
43 cost : 0.7016092
44 cost : 0.69277656
45 cost : 0.6872436
46 cost : 0.6839335
47 cost : 0.6810575
48 cost : 0.67725015
49 cost : 0.6720446
50 cost : 

404 cost : 0.24149933
405 cost : 0.2410606
406 cost : 0.240623
407 cost : 0.24018678
408 cost : 0.23975188
409 cost : 0.23931825
410 cost : 0.23888583
411 cost : 0.23845476
412 cost : 0.2380249
413 cost : 0.23759621
414 cost : 0.23716888
415 cost : 0.2367427
416 cost : 0.23631781
417 cost : 0.23589402
418 cost : 0.23547162
419 cost : 0.23505035
420 cost : 0.23463029
421 cost : 0.2342114
422 cost : 0.23379372
423 cost : 0.23337728
424 cost : 0.23296191
425 cost : 0.23254769
426 cost : 0.23213474
427 cost : 0.23172289
428 cost : 0.23131225
429 cost : 0.23090257
430 cost : 0.23049419
431 cost : 0.23008701
432 cost : 0.22968082
433 cost : 0.22927573
434 cost : 0.22887191
435 cost : 0.22846901
436 cost : 0.2280674
437 cost : 0.22766678
438 cost : 0.22726731
439 cost : 0.22686885
440 cost : 0.22647153
441 cost : 0.22607532
442 cost : 0.2256801
443 cost : 0.225286
444 cost : 0.22489293
445 cost : 0.2245008
446 cost : 0.22410983
447 cost : 0.22371994
448 cost : 0.22333108
449 cost : 0.22294329

812 cost : 0.1266711
813 cost : 0.12649032
814 cost : 0.12630989
815 cost : 0.1261298
816 cost : 0.12594998
817 cost : 0.12577057
818 cost : 0.1255914
819 cost : 0.1254126
820 cost : 0.12523417
821 cost : 0.12505594
822 cost : 0.1248782
823 cost : 0.12470072
824 cost : 0.12452349
825 cost : 0.124346726
826 cost : 0.124170154
827 cost : 0.12399399
828 cost : 0.123818174
829 cost : 0.123642616
830 cost : 0.123467445
831 cost : 0.123292424
832 cost : 0.12311789
833 cost : 0.122943655
834 cost : 0.122769676
835 cost : 0.12259605
836 cost : 0.12242273
837 cost : 0.12224978
838 cost : 0.122077115
839 cost : 0.12190473
840 cost : 0.12173272
841 cost : 0.121561036
842 cost : 0.121389575
843 cost : 0.121218435
844 cost : 0.121047616
845 cost : 0.12087721
846 cost : 0.12070701
847 cost : 0.12053714
848 cost : 0.12036756
849 cost : 0.12019833
850 cost : 0.12002946
851 cost : 0.11986085
852 cost : 0.11969256
853 cost : 0.11952442
854 cost : 0.11935677
855 cost : 0.11918937
856 cost : 0.119022295
8

In [16]:
w.numpy()
# w_a*1, w_a*2
# w_b*1 ..

array([[-0.04577604, -0.14389619, -0.39600635],
       [ 4.37027   ,  0.33310848, -3.6585474 ]], dtype=float32)

In [36]:
def hxfn( xdata):
    xd = tf.constant( xdata ,tf.float32)
    z = tf.matmul( xd, w) + b
    hx = tf.nn.softmax( z )
    return hx.numpy()
#     return hx.numpy().argmax(axis=1)
#     return z.numpy(), hx.numpy()

In [37]:
hxfn([[1,1], [2,2]])

array([[1.2624389e-19, 3.6771448e-09, 1.0000000e+00],
       [7.9406383e-15, 1.2152312e-06, 9.9999881e-01]], dtype=float32)

In [38]:
pred = hxfn( X ).argmax( axis=1)
pred

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [40]:
arr = np.array( [[1,2,3],[4,5,6]] )
arr.argmax(axis=1)

array([2, 2], dtype=int64)

In [39]:
pred = hxfn(X_data).argmax(axis = 1)

In [41]:
r = y_data.values.argmax(axis=1)
r

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [43]:
(pred==r).mean()

1.0

# Keras version

In [26]:
dense = Dense( units = 3, input_dim = 2, activation = 'sigmoid')
model = Sequential([dense])
model.compile(loss = 'categorical_crossentropy', optimizer = Adam(0.1), metrics = ['acc'])
h = model.fit( X, y, epochs = 1000)

Epoch 1/1000
1/1 [==============================] - 0s 0s/step - loss: 1.5890 - acc: 0.2500
Epoch 2/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2352 - acc: 0.2500
Epoch 3/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.1445 - acc: 0.3750
Epoch 4/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.1732 - acc: 0.2500
Epoch 5/1000
1/1 [==============================] - 0s 1000us/step - loss: 1.1803 - acc: 0.3750
Epoch 6/1000
1/1 [==============================] - 0s 0s/step - loss: 1.1579 - acc: 0.2500
Epoch 7/1000
1/1 [==============================] - 0s 0s/step - loss: 1.1175 - acc: 0.3750
Epoch 8/1000
1/1 [==============================] - 0s 0s/step - loss: 1.0731 - acc: 0.3750
Epoch 9/1000
1/1 [==============================] - 0s 0s/step - loss: 1.0383 - acc: 0.3750
Epoch 10/1000
1/1 [==============================] - 0s 0s/step - loss: 1.0197 - acc: 0.3750
Epoch 11/1000
1/1 [==============================] - 0s 0s/step - loss: 

1/1 [==============================] - 0s 0s/step - loss: 0.4655 - acc: 1.0000
Epoch 89/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.4625 - acc: 1.0000
Epoch 90/1000
1/1 [==============================] - 0s 999us/step - loss: 0.4596 - acc: 1.0000
Epoch 91/1000
1/1 [==============================] - 0s 0s/step - loss: 0.4568 - acc: 1.0000
Epoch 92/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.4540 - acc: 1.0000
Epoch 93/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.4514 - acc: 1.0000
Epoch 94/1000
1/1 [==============================] - 0s 0s/step - loss: 0.4487 - acc: 1.0000
Epoch 95/1000
1/1 [==============================] - 0s 999us/step - loss: 0.4461 - acc: 1.0000
Epoch 96/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.4435 - acc: 1.0000
Epoch 97/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.4410 - acc: 1.0000
Epoch 98/1000
1/1 [==============================] - 0s 0s/step 

1/1 [==============================] - 0s 1ms/step - loss: 0.3149 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.3137 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3126 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3115 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3104 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 0s/step - loss: 0.3093 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.3082 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3071 - acc: 1.0000
Epoch 182/1000
1/1 [==============================] - 0s 0s/step - loss: 0.3060 - acc: 1.0000
Epoch 183/1000
1/1 [==============================] - 0s 0s/step - loss: 0.3049 - acc: 1.0000
Epoch 184/1000
1/1 [==============================] - 0s 1ms/s

1/1 [==============================] - 0s 0s/step - loss: 0.2390 - acc: 1.0000
Epoch 261/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2384 - acc: 1.0000
Epoch 262/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.2377 - acc: 1.0000
Epoch 263/1000
1/1 [==============================] - 0s 999us/step - loss: 0.2370 - acc: 1.0000
Epoch 264/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2363 - acc: 1.0000
Epoch 265/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2356 - acc: 1.0000
Epoch 266/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2350 - acc: 1.0000
Epoch 267/1000
1/1 [==============================] - 0s 999us/step - loss: 0.2343 - acc: 1.0000
Epoch 268/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2336 - acc: 1.0000
Epoch 269/1000
1/1 [==============================] - 0s 999us/step - loss: 0.2329 - acc: 1.0000
Epoch 270/1000
1/1 [==============================] - 0s 1

Epoch 346/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1894 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1889 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1884 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1880 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1875 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1870 - acc: 1.0000
Epoch 352/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1865 - acc: 1.0000
Epoch 353/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1861 - acc: 1.0000
Epoch 354/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1856 - acc: 1.0000
Epoch 355/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1851 - acc: 1.0000
Epoch 356/1000
1/1 [=============

1/1 [==============================] - 0s 1ms/step - loss: 0.1539 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1535 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1532 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1528 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1525 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1521 - acc: 1.0000
Epoch 437/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1517 - acc: 1.0000
Epoch 438/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1514 - acc: 1.0000
Epoch 439/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1510 - acc: 1.0000
Epoch 440/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1507 - acc: 1.0000
Epoch 441/1000
1/1 [==============================] - 0s 1ms/s

1/1 [==============================] - 0s 1ms/step - loss: 0.1268 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1265 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1262 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1259 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1257 - acc: 1.0000
Epoch 522/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1254 - acc: 1.0000
Epoch 523/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1251 - acc: 1.0000
Epoch 524/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1249 - acc: 1.0000
Epoch 525/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1246 - acc: 1.0000
Epoch 526/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1243 - acc: 1.0000
Epoch 527/1000
1/1 [==============================] - 0s 0s/

1/1 [==============================] - 0s 0s/step - loss: 0.1059 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1056 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.1054 - acc: 1.0000
Epoch 606/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1052 - acc: 1.0000
Epoch 607/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1050 - acc: 1.0000
Epoch 608/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1048 - acc: 1.0000
Epoch 609/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1046 - acc: 1.0000
Epoch 610/1000
1/1 [==============================] - 0s 0s/step - loss: 0.1044 - acc: 1.0000
Epoch 611/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1042 - acc: 1.0000
Epoch 612/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1040 - acc: 1.0000
Epoch 613/1000
1/1 [==============================] - 0s 1ms/step

1/1 [==============================] - 0s 1ms/step - loss: 0.0895 - acc: 1.0000
Epoch 690/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0893 - acc: 1.0000
Epoch 691/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0891 - acc: 1.0000
Epoch 692/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0890 - acc: 1.0000
Epoch 693/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0888 - acc: 1.0000
Epoch 694/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0886 - acc: 1.0000
Epoch 695/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0885 - acc: 1.0000
Epoch 696/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0883 - acc: 1.0000
Epoch 697/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0881 - acc: 1.0000
Epoch 698/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0880 - acc: 1.0000
Epoch 699/1000
1/1 [==============================] - 0s 0s/step - lo

Epoch 775/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0764 - acc: 1.0000
Epoch 776/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0763 - acc: 1.0000
Epoch 777/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0762 - acc: 1.0000
Epoch 778/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0760 - acc: 1.0000
Epoch 779/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0759 - acc: 1.0000
Epoch 780/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0758 - acc: 1.0000
Epoch 781/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0756 - acc: 1.0000
Epoch 782/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0755 - acc: 1.0000
Epoch 783/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0754 - acc: 1.0000
Epoch 784/1000
1/1 [==============================] - 0s 995us/step - loss: 0.0752 - acc: 1.0000
Epoch 785/1000
1/1 [=======================

1/1 [==============================] - 0s 998us/step - loss: 0.0659 - acc: 1.0000
Epoch 862/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0658 - acc: 1.0000
Epoch 863/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0657 - acc: 1.0000
Epoch 864/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0656 - acc: 1.0000
Epoch 865/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0655 - acc: 1.0000
Epoch 866/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0654 - acc: 1.0000
Epoch 867/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0653 - acc: 1.0000
Epoch 868/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0652 - acc: 1.0000
Epoch 869/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0650 - acc: 1.0000
Epoch 870/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0649 - acc: 1.0000
Epoch 871/1000
1/1 [==============================] - 0s 0

1/1 [==============================] - 0s 1ms/step - loss: 0.0573 - acc: 1.0000
Epoch 948/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0573 - acc: 1.0000
Epoch 949/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0572 - acc: 1.0000
Epoch 950/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.0571 - acc: 1.0000
Epoch 951/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0570 - acc: 1.0000
Epoch 952/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0569 - acc: 1.0000
Epoch 953/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0568 - acc: 1.0000
Epoch 954/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0567 - acc: 1.0000
Epoch 955/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.0566 - acc: 1.0000
Epoch 956/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0565 - acc: 1.0000
Epoch 957/1000
1/1 [==============================] - 0s 

In [27]:
w, b = dense.get_weights()

In [29]:
w, b

(array([[-2.1812873, -2.2813094, -2.519056 ],
        [ 3.9411786, -1.2075365, -6.770344 ]], dtype=float32),
 array([-29.726439 ,  -0.3827594,  24.838924 ], dtype=float32))

In [44]:
def result_FN(dt):
    n = int( model.predict( dt ).argmax( axis = 1))
    grade = ['A', 'B', 'C']
    return grade[n]

In [47]:
result_FN([[5, 6]])

'A'

In [46]:
pred = model.predict(X).argmax(axis = 1)