In [87]:
ls

 C 드라이브의 볼륨: OS
 볼륨 일련 번호: BEAD-E4AA

 C:\Users\13a71\Dropbox\python숙달 디렉터리

2021-11-24  오후 02:01    <DIR>          .
2021-11-24  오후 02:01    <DIR>          ..
2021-11-24  오전 09:47    <DIR>          .ipynb_checkpoints
2021-11-23  오전 09:36    <DIR>          CODING TEST
2021-11-24  오후 02:01            75,687 day102_np.ipynb
2021-11-23  오전 11:32    <DIR>          numpy
2021-11-23  오후 02:48            53,163 NUMPY.ipynb
2021-11-24  오후 01:31            30,159 Numpy_Quiz.ipynb
               3개 파일             159,009 바이트
               5개 디렉터리  17,963,618,304 바이트 남음


In [2]:
ls data

 C 드라이브의 볼륨: OS
 볼륨 일련 번호: BEAD-E4AA

 C:\Users\13a71\Dropbox\python숙달 디렉터리



파일을 찾을 수 없습니다.


In [3]:
import os 

# 현재 작업폴더 위치 확인 
os.getcwd()

'C:\\Users\\13a71\\Dropbox\\python숙달'

In [4]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

# Numpy 개요

- Numeric + Python = Numpy
- 수학 및 과학 연산을 위한 파이썬 패키지
- 배열이나 행렬 계산에 용이한 메서드를 제공
- 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
- 관련 사이트 : http://www.numpy.or

# Numpy 임포트 및 정보 확인 

In [5]:
import numpy as np

In [6]:
#  버전 확인 
np.__version__

'1.20.1'

In [7]:
# 메소드와 속성 확인 
# print(dir(np))

In [8]:
# 넘파이 각 속성과 메서드 레퍼런스 확인은?
# 넘파이명령어?
np.mean?

# 넘파이 배열 생성 

- 리스트 => 넘파이 배열 
```
np.array(리스트)
```
- 관련 속성 
```
ndim : 차원 반환 => int
size : 전체 길이 반환  => int
shape : 구조 반환 => tuple 
```

In [9]:
# 1차원 리스트 => 1차원 넘파이 배열 
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList) )

[10, 56, 77, 23, 44] <class 'list'> 5


In [10]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr) )
print(f'차원은? {myArr.ndim}')
print(f'구조는? {myArr.shape}, {type(myArr.shape)}')
print(f'길이는? {myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원은? 1
구조는? (5,), <class 'tuple'>
길이는? 5


In [11]:
# print() 문을 사용하지 않고 넘파이 배열 출력
myArr

array([10, 56, 77, 23, 44])

In [12]:
# 2차원 리스트 => 넘파이 배열 
myList2 = [[1, 2, 3], [10, 20, 30], [100, 200, 300]]
myList2

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [13]:
myArr2 = np.array(myList2)
# len() 결과값이 2차원인 경우에는 행수로 출력 
print(myArr2, type(myArr2), len(myArr2) )
print(f'차원은? {myArr2.ndim}')
print(f'구조는? {myArr2.shape}, {type(myArr2.shape)}')
print(f'길이는? {myArr2.size}')
print(f'넘파이 배열은 {myArr2.shape[0]} 행 {myArr2.shape[1]} 열')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원은? 2
구조는? (3, 3), <class 'tuple'>
길이는? 9
넘파이 배열은 3 행 3 열


In [14]:
myArr2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [15]:
# 2차원 리스트에서 각 행 수가 틀린 경우 테스트 
# 넘파이 배열은?
myList3 = [[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]]
myList3, len(myList3)

([[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]], 3)

In [16]:
# 각행의 갯수가 틀린 경우  넘파이배열로 생성하면 
# list([값...]) 형태로 삽입된다. 
myArr3 = np.array(myList3)
myArr3

array([list([1, 2]), list([10, 20, 30]), list([100, 200, 300, 400, 500])],
      dtype=object)

# 넘파이 배열과 리스트와의 차이점은?

- 연산이 가능 => 브로드캐스팅 
- 배열간의 연산도 가능 
- 리스트는 자료형 혼합 가능. 넘파이 배열은 하나의 자료형만 가능 
- 넘파이에서 지원되는 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차, 최빈값

In [17]:
# 리스트의 경우 + - 리스트간의 연결 
listA = [10, 40, 50]
listB = [10, 40, 50]
listA + listB

[10, 40, 50, 10, 40, 50]

In [18]:
# 리스트의 경우 * - 리스트의 반복 
# listA * listB => Type error
listA * 2

[10, 40, 50, 10, 40, 50]

In [19]:
# 넘파이 배열간의 연산 
# 각 위치에 해당하는 요소간의 연산으로 반환 
arrA = np.array([10, 40, 50])
arrB = np.array([5, 4, 3])
print(arrA + arrB)
print(arrA - arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB)
print(arrA % arrB)

[15 44 53]
[ 5 36 47]
[ 50 160 150]
[ 2.         10.         16.66666667]
[ 2 10 16]
[0 0 2]


In [20]:
# 브로드캐스팅 
# 넘파이배열 연산자 숫자 
# 넘파이배열 각각에 연산이 적용된다. 
arrA
print(arrA)
print(arrA * 2)
print(arrA // 3)

[10 40 50]
[ 20  80 100]
[ 3 13 16]


In [21]:
# 리스트와 넘파이배열의 자료형 테스트 
myList_c = ['홍길동', 100, 3.14, True, False]
myList_c, type(myList_c)

(['홍길동', 100, 3.14, True, False], list)

In [22]:
# 넘파이 배열의 구성 요소의 자료형 확인은?
# 넘파이배열명.dtype

# 데이타가 혼합되어 있는 경우 자동형변환이 된다. 
# 문자열 넘파이 배열로 변경 
myArr_c = np.array(['홍길동', 100, 3.14, True, False])
myArr_c, type(myArr_c), myArr_c.dtype

(array(['홍길동', '100', '3.14', 'True', 'False'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [23]:
# 정수랑 실수 혼합된 넘파이 배열 생성 
myArr_d = np.array([100, 3.14, 23.5, 0])
myArr_d, type(myArr_d), myArr_d.dtype

(array([100.  ,   3.14,  23.5 ,   0.  ]), numpy.ndarray, dtype('float64'))

In [24]:
# 통계함수 적용하기 
# np.통계함수명(넘파이배열명, 옵션)
# 넘파이배열명.통계함수명(옵션)
myArr_d

array([100.  ,   3.14,  23.5 ,   0.  ])

In [25]:
print(f' 배열의 모든합은? {np.sum(myArr_d)}  {myArr_d.sum()}')
print(f' 배열의 평균은? {np.mean(myArr_d)}  {myArr_d.mean()}')
print(f' 배열의 최댓값은? {np.max(myArr_d)}  {myArr_d.max()}')
print(f' 배열의 최솟값은? {np.min(myArr_d)}  {myArr_d.min()}')

 배열의 모든합은? 126.64  126.64
 배열의 평균은? 31.66  31.66
 배열의 최댓값은? 100.0  100.0
 배열의 최솟값은? 0.0  0.0


In [26]:
print(f' 배열의 중앙값은? {np.median(myArr_d)}')

 배열의 중앙값은? 13.32


In [27]:
# 아래는 에러발생함 중앙값을 출력하는 함수의 경우 
# AttributeError 
# np.median(넘파이배열) 만 됨 
# print(f' 배열의 중앙값은? {myArr_d.median()}')

In [28]:
# 넘파이 제공 함수를 이용해서 배열 생성하기 

```
np.ones(n) , np.ones((x, y)) 
np.zeros(n) , np.zeros((x, y))
np.arange(start, end, step) 

# 1차원 => 2차원
reshape(x, y)
# 2차원 => 1차원
flatten()
```

NameError: name 'n' is not defined

In [29]:
# 1. 로 구성된 넘파이 배열 생성 
arr1 = np.ones(10)
arr1, arr1.dtype

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), dtype('float64'))

In [30]:
# 1 로 구성된 넘파이 배열 생성 => 정수형 
arr2 = np.ones(10, dtype=int)
arr2, arr2.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), dtype('int32'))

In [31]:
# 1 로 구성된 5행 2열 배열 생성 => 정수형 
arr3 = np.ones((5,2), dtype=int)
arr3, arr3.dtype, arr3.shape

(array([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 dtype('int32'),
 (5, 2))

In [32]:
# 3행 3열 0으로 구성된 넘파이 배열 
print( np.array([[0,0,0], [0,0,0], [0,0,0]]) )
arr4 = np.zeros((3,3), dtype=int)
print('='*30)
print(arr4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
# 5행 5열로 구성된 넘파이 배열 
arr5 = np.empty((5,5))
arr5

array([[ 1.10754035e-311,  7.46039125e-322,  0.00000000e+000,
         0.00000000e+000,  7.56587583e-307],
       [ 1.16095484e-028, -9.27327519e-171, -5.75959776e+210,
         6.10738033e-152, -3.74043493e-074],
       [-1.58980714e+215, -4.29614932e-150,  1.03091574e-151,
         2.87786951e-014,  7.49232601e+247],
       [ 1.05016875e-153,  7.29882928e+223,  7.17466957e-061,
         3.73480841e+174,  9.13554114e+242],
       [ 4.24819624e+180,  2.91237123e+257,  4.71294503e+257,
         2.59819097e-306,  6.84366093e+193]])

In [45]:
# 1~20 으로 구성된 4행 5열의 넘파이 배열 

# range() 객체 => 리스트화 list(range()) => 넘파이 배열화 np.array(list(range()))
print(range(1,21), list(range(1,21)))
print(np.array(list(range(1,21))))
print('='*30)
arr6 = np.arange(1, 21).reshape(4, 5)
arr6

range(1, 21) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
# 1~20 으로 구성된 4행 5열의 넘파이 배열 

# range() 객체 => 리스트화 list(range()) => 넘파이 배열화 np.array(list(range()))
print(range(1,21), list(range(1,21)))
print(np.array(list(range(1,21))))
print('='*30)
# reshape(x, y) => x행 y열 로 재구성 
arr6 = np.arange(1, 21).reshape(4, 5)
arr6

range(1, 21) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
# 0~49 까지 구성된 넘파이 배열
# 초기값이 0인 경우 생략 가능 
arr7 = np.arange(50)
print(arr7, len(arr7), arr7.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [48]:
# 원본 넘파이 배열에 다시 적용 
arr7 = arr7.reshape(10,5)
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [49]:
# 2차원 => 2차원 변경 가능 
arr7.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
# 2차원 => 2차원 변경 가능 
arr8 = arr7.reshape(5,10)
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
# 2차원 => 1차원으로 변경 
arr8.ndim, arr8.shape

(2, (5, 10))

In [52]:
# 2차원 => 1차원으로 변경 
# 넘파이배열.flatten()
arr8.ndim, arr8.shape

(2, (5, 10))

In [53]:
arr9 = arr8.flatten()
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [54]:
# 0~100 사이의 숫자중에서 짝수로된 넘파이 배열 생성
arr10 = np.arange(0, 101, 2)
arr10

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [55]:
# 0~100 사이의 숫자중에서 짝수로된 넘파이 배열 생성
arr10 = np.arange(0, 101, 2)
arr10

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [56]:
# 홀수는?
np.arange(1, 101, 2).reshape(25,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23],
       [25, 27],
       [29, 31],
       [33, 35],
       [37, 39],
       [41, 43],
       [45, 47],
       [49, 51],
       [53, 55],
       [57, 59],
       [61, 63],
       [65, 67],
       [69, 71],
       [73, 75],
       [77, 79],
       [81, 83],
       [85, 87],
       [89, 91],
       [93, 95],
       [97, 99]])

In [57]:
# reshape(-1, n) => 2차원 n개의 컬럼으로 구성 
arr12 = arr11.reshape(-1, 1)
arr12, arr12.ndim

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2)

In [43]:
arr11, arr11.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 1)

In [44]:
arr12 = arr11.reshape(-1,1)
arr12, arr12.ndim

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2)

In [58]:
np.arange(1,21).reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [59]:
# np.arange(1,21).reshape(10, 2)
np.arange(1,21).reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [62]:
# 정수형, 3행 3열
matrix = np.arange(1,10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [63]:
# 실수형, 3행 3열
matrix = np.arange(1,10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [65]:
# 문자열형, 3행 3열
matrix = np.arange(1,10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [66]:
# 정수형 => 문자열형 
matrix.astype('<U5')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U5')

In [67]:
# 논리형으로 구성된 넘파이 배열 생성 
matrix2 = np.array([True, False, True, True, False])
matrix2, matrix2.dtype

(array([ True, False,  True,  True, False]), dtype('bool'))

In [68]:
# 논리형 => 정수형 
# True => 1, False => 0
matrix2.astype(int), matrix2.astype(int).dtype

(array([1, 0, 1, 1, 0]), dtype('int32'))

In [69]:
# 논리형 => 문자열 
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True', 'False'], dtype='<U5')

In [70]:
# 문자열숫자 => 정수나 실수 
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3

array(['3.14', '5.5', '0.78'], dtype='<U4')

In [71]:
matrix3.astype(float), matrix3.astype(float).dtype

(array([3.14, 5.5 , 0.78]), dtype('float64'))

In [72]:
matrix4 = np.array(['3', '5', '0'])
matrix4.astype(int)

array([3, 5, 0])

In [74]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

In [75]:
matrix_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
# 1차원에서 첫요소와 마지막 요소 
matrix_a[0], matrix_a[-1]

(0, 9)

In [81]:
# 2차원에서 1행 1열 
matrix_b[0,0], matrix_b[0][0]

(0, 0)

In [82]:
# 2차원에서 마지막 행, 마지막열
matrix_b[-1, -1], matrix_b[-1][-1], matrix_b[2][3]


(11, 11, 11)

In [86]:
matrix_b[2,0]= 100
matrix_b[2,0]

100

NameError: name 'pd' is not defined