In [1]:
import os
import numpy as np

In [2]:
os.getcwd()

'C:\\Users\\13a71\\Dropbox\\python숙달\\numpy'

In [4]:
os.chdir('C:/Users/13a71/Downloads/data')

In [5]:
ls data

 C 드라이브의 볼륨: OS
 볼륨 일련 번호: BEAD-E4AA

 C:\Users\13a71\Downloads\data\data 디렉터리

2021-11-23  오전 10:54    <DIR>          .
2021-11-23  오전 10:54    <DIR>          ..
2021-11-23  오전 09:12             3,088 births.txt
2021-11-23  오전 09:25            35,455 Jeju2021.csv
2016-07-18  오전 06:46           171,308 movies.dat
2018-04-24  오후 07:42        24,594,131 ratings.dat
2019-03-20  오후 07:54         1,185,149 seoul.csv
2021-02-01  오전 05:49            93,805 seoul2021.csv
               6개 파일          26,082,936 바이트
               2개 디렉터리  17,832,910,848 바이트 남음


In [6]:
import numpy as np

In [7]:
np.__version__

'1.20.1'

In [8]:
mylist2 = [[1,2,3], [10,20, 30], [ 100,200,300]]

In [10]:
myList3 = [[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]]
myList3, len(myList3)

([[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]], 3)

In [11]:
arrA = np.array([10, 40, 50])
arrB = np.array([5, 4, 3])
print(arrA + arrB)
print(arrA - arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB)
print(arrA % arrB)

[15 44 53]
[ 5 36 47]
[ 50 160 150]
[ 2.         10.         16.66666667]
[ 2 10 16]
[0 0 2]


In [12]:
# 넘파이 배열의 구성 요소의 자료형 확인은?
# 넘파이배열명.dtype
myArr_c = np.array(['홍길동', 100, 3.14, True, False])
myArr_c, type(myArr_c), myArr_c.dtype

(array(['홍길동', '100', '3.14', 'True', 'False'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))